// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4IkUmhhr0NM6fHQx_mhOFkGxcLMurr8',
    appId: '1:1006326469621:web:e13bffc4723ed472b606bc',
    messagingSenderId: '1006326469621',
    projectId: 'final-year-project-387ca',
    authDomain: 'final-year-project-387ca.firebaseapp.com',
    storageBucket: 'final-year-project-387ca.firebasestorage.app',
    measurementId: 'G-6L11M6C347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloMc_k2z9wbcKq2ajjIsPw4WLvLZ0Gdw',
    appId: '1:1006326469621:android:67d6bb5214484cbcb606bc',
    messagingSenderId: '1006326469621',
    projectId: 'final-year-project-387ca',
    storageBucket: 'final-year-project-387ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjhUb_Z2ncHZHEjWqy7eXlu5tpwEQFZU',
    appId: '1:1006326469621:ios:374e377371c0c57eb606bc',
    messagingSenderId: '1006326469621',
    projectId: 'final-year-project-387ca',
    storageBucket: 'final-year-project-387ca.firebasestorage.app',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
